version: "3"
services:
  db:
    container_name: 'tracker_DB'
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ~/Documents/tracker-db-data:/var/lib/postgresql/data/
      - ./db/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
